### ISSUE TITLE
Sequence in the hint - shouldn't it be white?

### ISSUE THREAD

**Issue by olekstomek** [martaProsniak/mastermind#3]
My case:
![mastermind_3_black_dots_why_not_white](https://github.com/martaProsniak/mastermind/assets/26818304/241afa20-f1d0-4b03-a357-833384ef1cfc)
Green, red and pink balls are on the correct position so hint has three black dots. It's fine. But hint has also gray dots what means that colors in my row is not included. But it is red so it is included in my row. So instead of gray, shouldn't I see white (which would tell me that I should use one of the three colors in the current row again)?

**Comment by martaProsniak** [comment]
It works as expected. White would be displayed if you would have one more, red guess, but in the wrong position. In your example there are 3 correct guesses (marked with black) and one incorrect color (pink color instead of red), which is marked gray. There is no direct indicator for color count in the sequence. If there would be a sequence consisted of 4 red colors and the user would use red only once in their guess, only one occurrence would be classified as the correct one and other 3 guesses would be incorrect. 

Attaching screen from example gameplay, hope it'll make it more clear :)
![image](https://github.com/martaProsniak/mastermind/assets/47717841/0f6924fb-09a9-4d3b-af44-09ae689fe8ad)

**Comment by olekstomek** [comment]
Yes, it's clear. Thanks for clarification! :)
